### ISSUE TITLE
[テスト] GTDフロー 網羅的自動テストの実装

### ISSUE THREAD

**Issue by chittai** [chittai/task-manager#98]
# 🧪 概要

GTDフローの全6ステップと代替パスの自動テストを強化し、Playwrightによる網羅的なE2Eテストスイートを構築する。

## 🎯 目的

現在のGTDフローテストは基本的な機能のみをカバーしており、以下の強化が必要：

- 全6ステップの遷移テスト
- 代替パス（行動不要、プロジェクト、委任等）のテスト
- エラーケースとエッジケースのテスト
- パフォーマンステスト

### 1. 基本フローテストの強化

**ファイル**: `tests/gtdFlowComplete.test.ts`

```typescript
test.describe('GTDフロー完全テスト', () => {
  test('主要フロー: 単一アクション → 次のアクション', async ({ page }) => {
    // Step 1: それは何か？
    await page.goto('/');
    await page.click('text=GTD処理を開始');
    await page.fill('input[placeholder*="アイテム"]', 'テストタスク');
    await page.click('button:has-text("次へ")');
    
    // Step 2: 行動を起こす必要があるか？
    await page.click('input[value=\"yes\"]');
    await page.click('button:has-text("次へ")');
    
    // Step 3: 1つか複数か？
    await page.click('input[value=\"single\"]');
    await page.click('button:has-text("次へ")');
    
    // Step 4: 2分ルール
    await page.click('input[value=\"no\"]');
    await page.click('button:has-text("次へ")');
    
    // Step 5: 自分でやるか？
    await page.click('input[value=\"myself\"]');
    await page.click('button:has-text("次へ")');
    
    // Step 6: 特定の日時？
    await page.click('input[value=\"no\"]');
    await page.click('button:has-text("完了")');
    
    // 結果確認
    await expect(page.locator('text=次のアクション')).toBeVisible();
  });
});
```

### 2. 代替パステスト

**テストケース**:
- 行動不要 → 参考資料
- 行動不要 → いつかやる
- 行動不要 → ゴミ箱
- 複数アクション → プロジェクト
- 2分ルール → 即実行
- 委任 → 待機中

### 3. エラーケーステスト

**テストケース**:
- 必須フィールド未入力
- 無効な日付入力
- ネットワークエラー時の挙動
- タスク作成失敗時の処理

### 4. パフォーマンステスト

```typescript
test('GTDフロー パフォーマンス', async ({ page }) => {
  const startTime = Date.now();
  
  // 全ステップを最速で実行
  await executeFullGtdFlow(page);
  
  const endTime = Date.now();
  const duration = endTime - startTime;
  
  expect(duration).toBeLessThan(5000); // 5秒以内
});
```

### 5. 視覚的回帰テスト

```typescript
test('GTDフロー 視覚的確認', async ({ page }) => {
  await page.goto('/');
  await page.click('text=GTD処理を開始');
  
  // 各ステップのスクリーンショット
  for (let step = 1; step <= 6; step++) {
    await expect(page).toHaveScreenshot(`step-${step}.png`);
    if (step < 6) {
      await proceedToNextStep(page, step);
    }
  }
});
```

### 6. 並行テスト

```typescript
test.describe.parallel('GTDフロー 並行テスト', () => {
  test('フロー1: 参考資料パス', async ({ page }) => { /* ... */ });
  test('フロー2: プロジェクトパス', async ({ page }) => { /* ... */ });
  test('フロー3: 委任パス', async ({ page }) => { /* ... */ });
});
```

### 機能カバレッジ
- [ ] 主要フロー: 6ステップ全て ✅
- [ ] 代替パス: 8パターン ✅
- [ ] エラーケース: 12シナリオ ✅
- [ ] エッジケース: 6シナリオ ✅

### コードカバレッジ
- [ ] GTDフロー関連ファイル: 90%以上
- [ ] 重要な関数: 100%
- [ ] エラーハンドリング: 85%以上

### 基本要件
- [ ] 全6ステップの遷移テスト
- [ ] 8つの代替パスのテスト
- [ ] エラーケースの網羅的テスト
- [ ] パフォーマンステストの実装

### 品質要件
- [ ] テスト実行時間: 5分以内
- [ ] 成功率: 99%以上
- [ ] 並行実行対応
- [ ] CI/CDパイプライン統合

### 運用要件
- [ ] テストレポートの自動生成
- [ ] 失敗時のスクリーンショット
- [ ] ログ・トレース情報の収集
- [ ] 定期実行スケジュール

### ローカル実行
```bash
# 全GTDフローテスト
npm run test:gtd

# 特定パスのみ
npm run test:gtd -- --grep \"参考資料\"

# デバッグモード
npm run test:gtd:debug
```

### CI/CD設定
```yaml
# .github/workflows/gtd-flow-tests.yml
name: GTD Flow Tests
on: [push, pull_request]
jobs:
  gtd-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run GTD Flow Tests
        run: npm run test:gtd
      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: gtd-test-results
          path: test-results/
```

## 🔗 関連Issue

- #95 (GTDフロー ステップ遷移問題)
- #96 (状態管理とDOM同期の強化)
- #97 (デバッグ機能とツールの追加)

## 🎯 優先度
**High** - 品質保証の基盤となる重要な機能

## 📝 実装ガイド

1. **Phase 1**: 基本フローテストの実装
2. **Phase 2**: 代替パステストの追加
3. **Phase 3**: エラーケース・エッジケースの実装
4. **Phase 4**: パフォーマンス・視覚テストの追加
5. **Phase 5**: CI/CD統合とレポート機能
